-- MySQL Script generated by MySQL Workbench
-- Fri Apr 13 00:42:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_seguros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_seguros` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carreras` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `id_departamento` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC),
  INDEX `id_departamento` (`id_departamento` ASC),
  CONSTRAINT `carreras_ibfk_1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`departamentos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(60) NOT NULL,
  `contrasenia` VARCHAR(100) NOT NULL,
  `rol` ENUM('candidato_residente', 'residente', 'docente', 'admin', 'jefe_departamento', 'asesor_externo', 'subdirector_academico') NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alumnos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `no_control` VARCHAR(8) NOT NULL,
  `plan_estudios` ENUM('2009-2010', '2015-2016') NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `ap_paterno` VARCHAR(30) NOT NULL,
  `ap_materno` VARCHAR(30) NOT NULL,
  `sexo` ENUM('H', 'M') NULL DEFAULT NULL,
  `domicilio` VARCHAR(200) NULL DEFAULT NULL,
  `colonia` VARCHAR(30) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(5) NULL DEFAULT NULL,
  `no_seguro` VARCHAR(20) NULL DEFAULT NULL,
  `numero_celular` VARCHAR(20) NULL DEFAULT NULL,
  `ciudad` VARCHAR(150) NOT NULL DEFAULT '',
  `id_tipo_seguro` INT(11) NULL DEFAULT NULL,
  `id_carrera` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `no_control` (`no_control` ASC),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC),
  INDEX `id_tipo_seguro` (`id_tipo_seguro` ASC),
  INDEX `id_carrera` (`id_carrera` ASC),
  CONSTRAINT `alumnos_ibfk_1`
    FOREIGN KEY (`id_tipo_seguro`)
    REFERENCES `mydb`.`tipo_seguros` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `alumnos_ibfk_2`
    FOREIGN KEY (`id_carrera`)
    REFERENCES `mydb`.`carreras` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `alumnos_ibfk_3`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`periodos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `periodo` ENUM('FEBRERO-JUNIO', 'AGOSTO-DICIEMBRE') NOT NULL,
  `ciclo` VARCHAR(4) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `fecha_inicio_entrega_anteproyecto` DATE NOT NULL,
  `fecha_fin_entrega_anteproyecto` DATE NOT NULL,
  `filename_dictamen` VARCHAR(255) NULL DEFAULT NULL,
  `id_carrera` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_uq_periodo_ciclo` (`periodo` ASC, `ciclo` ASC, `id_carrera` ASC),
  INDEX `id_carrera` (`id_carrera` ASC),
  CONSTRAINT `periodos_ibfk_1`
    FOREIGN KEY (`id_carrera`)
    REFERENCES `mydb`.`carreras` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`titulares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`titulares` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `puesto` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `clasificacion` ENUM('industrial', 'servicios', 'público', 'privado', 'otro') NOT NULL,
  `rfc` VARCHAR(13) NULL DEFAULT NULL,
  `domicilio` VARCHAR(100) NULL DEFAULT NULL,
  `colonia` VARCHAR(100) NULL DEFAULT NULL,
  `mision` VARCHAR(600) NOT NULL DEFAULT '',
  `codigo_postal` VARCHAR(5) NULL DEFAULT NULL,
  `fax` VARCHAR(15) NULL DEFAULT NULL,
  `id_titular` INT(11) NOT NULL,
  `id_representante_legal` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre` (`nombre` ASC),
  INDEX `fk_titular_empresa` (`id_titular` ASC),
  INDEX `fk_representante_legal_empresa` (`id_representante_legal` ASC),
  CONSTRAINT `fk_representante_legal_empresa`
    FOREIGN KEY (`id_representante_legal`)
    REFERENCES `mydb`.`titulares` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_titular_empresa`
    FOREIGN KEY (`id_titular`)
    REFERENCES `mydb`.`titulares` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`asesor_externos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asesor_externos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `puesto` VARCHAR(100) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `id_empresa` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC),
  INDEX `id_empresa` (`id_empresa` ASC),
  CONSTRAINT `asesor_externos_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `asesor_externos_ibfk_2`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `mydb`.`empresas` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`docentes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  `ap_paterno` VARCHAR(30) NOT NULL,
  `ap_materno` VARCHAR(30) NOT NULL,
  `titulo` VARCHAR(10) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `id_departamento` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_usuario` (`id_usuario` ASC),
  INDEX `id_departamento` (`id_departamento` ASC),
  CONSTRAINT `docentes_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `docentes_ibfk_2`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`departamentos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`anteproyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`anteproyectos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(600) NULL DEFAULT NULL,
  `objetivo_general` VARCHAR(600) NULL DEFAULT NULL,
  `origen` ENUM('Banco de proyectos', 'Propuesta propia', 'Trabajador') NULL DEFAULT NULL,
  `dictamen` ENUM('aprobado', 'no aprobado') NOT NULL DEFAULT 'no aprobado',
  `path_file_anteproyecto` VARCHAR(255) NULL DEFAULT NULL,
  `id_alumno` INT(11) NOT NULL,
  `id_periodo` INT(11) NOT NULL,
  `id_asesor_externo` INT(11) NULL DEFAULT NULL,
  `id_asesor_interno` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_alumno` (`id_alumno` ASC),
  INDEX `id_periodo` (`id_periodo` ASC),
  INDEX `id_asesor_externo` (`id_asesor_externo` ASC),
  INDEX `id_asesor_interno` (`id_asesor_interno` ASC),
  CONSTRAINT `anteproyectos_ibfk_1`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `mydb`.`alumnos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `anteproyectos_ibfk_2`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `mydb`.`periodos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `anteproyectos_ibfk_3`
    FOREIGN KEY (`id_asesor_externo`)
    REFERENCES `mydb`.`asesor_externos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `anteproyectos_ibfk_4`
    FOREIGN KEY (`id_asesor_interno`)
    REFERENCES `mydb`.`docentes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`evaluaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evaluaciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `observaciones` VARCHAR(500) NOT NULL DEFAULT '',
  `tipo` ENUM('asesor_externo', 'asesor_interno') NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyectos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `filename_plan_trabajo` VARCHAR(200) NULL DEFAULT NULL,
  `aprobacion_plan_trabajo` TINYINT(1) NULL DEFAULT '0',
  `filename_cronograma` VARCHAR(200) NULL DEFAULT NULL,
  `aprobacion_cronograma` TINYINT(1) NULL DEFAULT '0',
  `url_informe_tecnico` VARCHAR(300) NULL DEFAULT NULL,
  `autorizar_carta_liberacion_asesor_interno` TINYINT(1) NULL DEFAULT '0',
  `autorizar_carta_liberacion_asesor_externo` TINYINT(1) NULL DEFAULT '0',
  `id_anteproyecto` INT(11) NOT NULL,
  `id_evaluacion_asesor_interno` INT(11) NULL DEFAULT NULL,
  `id_evaluacion_asesor_externo` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_anteproyecto` (`id_anteproyecto` ASC),
  INDEX `fkey_id_evaluacion_asesor_interno` (`id_evaluacion_asesor_interno` ASC),
  INDEX `fkey_id_evaluacion_asesor_externo` (`id_evaluacion_asesor_externo` ASC),
  CONSTRAINT `fkey_id_evaluacion_asesor_externo`
    FOREIGN KEY (`id_evaluacion_asesor_externo`)
    REFERENCES `mydb`.`evaluaciones` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fkey_id_evaluacion_asesor_interno`
    FOREIGN KEY (`id_evaluacion_asesor_interno`)
    REFERENCES `mydb`.`evaluaciones` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `proyectos_ibfk_1`
    FOREIGN KEY (`id_anteproyecto`)
    REFERENCES `mydb`.`anteproyectos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`asesoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asesoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_proyecto` INT(11) NOT NULL,
  `id_asesor_interno` INT(11) NOT NULL,
  `permitir_generar_formato` TINYINT(1) NOT NULL DEFAULT '0',
  `tipo` ENUM('presencial', 'virtual') NOT NULL DEFAULT 'virtual',
  `fecha` DATE NOT NULL,
  `url_avance` VARCHAR(300) NOT NULL,
  `temas_a_asesorar` VARCHAR(500) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_proyecto` (`id_proyecto` ASC),
  INDEX `id_asesor_interno` (`id_asesor_interno` ASC),
  CONSTRAINT `asesoria_ibfk_1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyectos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `asesoria_ibfk_2`
    FOREIGN KEY (`id_asesor_interno`)
    REFERENCES `mydb`.`docentes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`cancelacion_proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cancelacion_proyectos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(255) NULL DEFAULT NULL,
  `justificacion` VARCHAR(255) NULL DEFAULT NULL,
  `id_alumno` INT(11) NOT NULL,
  `id_asesor_interno` INT(11) NULL DEFAULT NULL,
  `id_periodo` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_alumno` (`id_alumno` ASC),
  INDEX `id_asesor_interno` (`id_asesor_interno` ASC),
  INDEX `id_periodo` (`id_periodo` ASC),
  CONSTRAINT `cancelacion_proyectos_ibfk_1`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `mydb`.`alumnos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `cancelacion_proyectos_ibfk_2`
    FOREIGN KEY (`id_asesor_interno`)
    REFERENCES `mydb`.`docentes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `cancelacion_proyectos_ibfk_3`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `mydb`.`periodos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`criterios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`criterios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  `valor_max` INT(11) NULL DEFAULT NULL,
  `tipo` ENUM('asesor_externo', 'asesor_interno') NOT NULL,
  `anexo` VARCHAR(30) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`criterio_evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`criterio_evaluacion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_evaluacion` INT(11) NOT NULL,
  `valor_de_evaluacion` INT(11) NOT NULL,
  `id_criterio` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_evaluacion` (`id_evaluacion` ASC),
  INDEX `id_criterio` (`id_criterio` ASC),
  CONSTRAINT `criterio_evaluacion_ibfk_1`
    FOREIGN KEY (`id_evaluacion`)
    REFERENCES `mydb`.`evaluaciones` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `criterio_evaluacion_ibfk_2`
    FOREIGN KEY (`id_criterio`)
    REFERENCES `mydb`.`criterios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`docente_carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`docente_carreras` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_docente` INT(11) NOT NULL,
  `id_carrera` INT(11) NOT NULL,
  `rol` ENUM('docente', 'jefe_proyecto', 'presidente_academia', 'deshabilitado') NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index_uq_docente_carreras` (`id_docente` ASC, `id_carrera` ASC),
  INDEX `id_carrera` (`id_carrera` ASC),
  CONSTRAINT `docente_carreras_ibfk_1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `mydb`.`docentes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `docente_carreras_ibfk_2`
    FOREIGN KEY (`id_carrera`)
    REFERENCES `mydb`.`carreras` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`observaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`observaciones` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_proyecto` INT(11) NOT NULL,
  `id_asesor_interno` INT(11) NOT NULL,
  `observacion` VARCHAR(500) NULL DEFAULT NULL,
  `solucionada` TINYINT(1) NULL DEFAULT '0',
  `tipo` ENUM('plan_de_trabajo', 'cronograma') NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_proyecto` (`id_proyecto` ASC),
  INDEX `id_asesor_interno` (`id_asesor_interno` ASC),
  CONSTRAINT `observaciones_ibfk_1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyectos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `observaciones_ibfk_2`
    FOREIGN KEY (`id_asesor_interno`)
    REFERENCES `mydb`.`docentes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`revision_anteproyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`revision_anteproyectos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `esFactible` ENUM('factible', 'no_factible', 'corrección') NOT NULL DEFAULT 'no_factible',
  `comentario` VARCHAR(500) NULL DEFAULT NULL,
  `id_docente` INT(11) NOT NULL,
  `id_anteproyecto` INT(11) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniq_revision_anteproyectos_id_docente_id_anteproyecto` (`id_docente` ASC, `id_anteproyecto` ASC),
  INDEX `id_anteproyecto` (`id_anteproyecto` ASC),
  CONSTRAINT `revision_anteproyectos_ibfk_1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `mydb`.`docentes` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `revision_anteproyectos_ibfk_2`
    FOREIGN KEY (`id_anteproyecto`)
    REFERENCES `mydb`.`anteproyectos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`seguimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seguimientos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_periodo` INT(11) NOT NULL,
  `fecha_inicial` DATE NOT NULL,
  `fecha_final` DATE NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_periodo` (`id_periodo` ASC),
  CONSTRAINT `seguimientos_ibfk_1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `mydb`.`periodos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`seguimiento_proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seguimiento_proyectos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `url_seguimiento` VARCHAR(300) NULL DEFAULT NULL,
  `id_seguimiento` INT(11) NOT NULL,
  `id_proyecto` INT(11) NULL DEFAULT NULL,
  `id_evaluacion_asesor_interno` INT(11) NULL DEFAULT NULL,
  `id_evaluacion_asesor_externo` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_seguimiento` (`id_seguimiento` ASC),
  INDEX `id_proyecto` (`id_proyecto` ASC),
  INDEX `fkey_id_evaluacion_asesor_interno_seguimiento` (`id_evaluacion_asesor_interno` ASC),
  INDEX `fkey_id_evaluacion_asesor_externo_seguimiento` (`id_evaluacion_asesor_externo` ASC),
  CONSTRAINT `fkey_id_evaluacion_asesor_externo_seguimiento`
    FOREIGN KEY (`id_evaluacion_asesor_externo`)
    REFERENCES `mydb`.`evaluaciones` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fkey_id_evaluacion_asesor_interno_seguimiento`
    FOREIGN KEY (`id_evaluacion_asesor_interno`)
    REFERENCES `mydb`.`evaluaciones` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `seguimiento_proyectos_ibfk_1`
    FOREIGN KEY (`id_seguimiento`)
    REFERENCES `mydb`.`seguimientos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `seguimiento_proyectos_ibfk_2`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyectos` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`revision_seguimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`revision_seguimientos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_seguimiento_proyecto` INT(11) NOT NULL,
  `id_docente` INT(11) NOT NULL,
  `observacion` VARCHAR(500) NOT NULL,
  `solucionado` TINYINT(1) NOT NULL DEFAULT '0',
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_seguimiento_proyecto` (`id_seguimiento_proyecto` ASC),
  INDEX `id_docente` (`id_docente` ASC),
  CONSTRAINT `revision_seguimientos_ibfk_1`
    FOREIGN KEY (`id_seguimiento_proyecto`)
    REFERENCES `mydb`.`seguimiento_proyectos` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `revision_seguimientos_ibfk_2`
    FOREIGN KEY (`id_docente`)
    REFERENCES `mydb`.`docentes` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sequelizemeta` (
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC),
  UNIQUE INDEX `SequelizeMeta_name_unique` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`solucion_recomendadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solucion_recomendadas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_asesoria` INT(11) NOT NULL,
  `solucion` VARCHAR(255) NOT NULL,
  `solucionado` TINYINT(1) NOT NULL DEFAULT '0',
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_asesoria` (`id_asesoria` ASC),
  CONSTRAINT `solucion_recomendadas_ibfk_1`
    FOREIGN KEY (`id_asesoria`)
    REFERENCES `mydb`.`asesoria` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
